#!/usr/bin/env node
// Builds the browser runtime from grammar/grammar.json + src/core.mjs:
//
//   dist/grammar.runtime.json  the grammar minus evidence/refs — only the
//                              fields src/core.mjs reads
//   dist/validate.mjs          ONE self-contained ES module: core.mjs +
//                              the runtime grammar inlined + createValidator().
//                              ixmaps-gl lazy-loads it with import(url) when
//                              validation is on — one request, no deps.
//
// Usage: node scripts/build-runtime.mjs   (npm run build)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const grammar = JSON.parse(fs.readFileSync(path.join(ROOT, 'grammar', 'grammar.json'), 'utf8'));
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));

// the keyword sections core.mjs validates against
const SECTIONS = ['flags', 'styleKeys', 'bindingKeys', 'metaKeys', 'dataKeys', 'dataTypes', 'mapOptions',
  'optionsKeys', 'mapBuilderMethods', 'layerMethods', 'mapInstanceMethods', 'runtimeApi'];

// Keep exactly the per-entry fields core.mjs reads — everything else
// (evidence, refs, sources, target) is for humans and the extractor.
function slimEntry(e) {
  const o = {};
  if (e.gl) {
    o.gl = { status: e.gl.status };
    if (e.gl.note) o.gl.note = e.gl.note;
  }
  if (e.substringMatched) o.substringMatched = true;
  if (e.match) o.match = e.match;
  if (e.kind) o.kind = e.kind;
  return o;
}

const runtime = {
  $comment: 'GENERATED by scripts/build-runtime.mjs from grammar.json — do not edit',
  version: pkg.version,
  sources: grammar.sources,
  flagPatterns: Object.fromEntries(Object.keys(grammar.flagPatterns || {}).map(k => [k, {}])),
  glExtensions: grammar.glExtensions || {},
  glInternal: grammar.glInternal || {},
};
for (const s of SECTIONS) {
  runtime[s] = Object.fromEntries(Object.entries(grammar[s] || {}).map(([k, e]) => [k, slimEntry(e)]));
}

fs.mkdirSync(path.join(ROOT, 'dist'), { recursive: true });
const runtimeJson = JSON.stringify(runtime);
fs.writeFileSync(path.join(ROOT, 'dist', 'grammar.runtime.json'), runtimeJson + '\n');

const core = fs.readFileSync(path.join(ROOT, 'src', 'core.mjs'), 'utf8');
const module = `// ixmaps-grammar ${pkg.version} — runtime validator (GENERATED by scripts/build-runtime.mjs; do not edit)
// Source: src/core.mjs + grammar/grammar.json (ixmaps-flat ${grammar.sources?.flat?.version}, ${grammar.sources?.flat?.commit}; ixmaps-gl ${grammar.sources?.gl?.commit})
//
//   const { createValidator } = await import('.../validate.mjs');
//   const v = createValidator({ engine: 'gl', onFinding: (f, ctx) => ... });
//   v.theme({ type, style, meta, binding, data }, { layer: 'name' });
//   v.options({...}); v.mapOptions({...}); v.style({...}); v.runtimeCall('setMapTool');

${core}

export const GRAMMAR = ${runtimeJson};

export const version = GRAMMAR.version;

export function createValidator(opts = {}) {
  return new Validator(GRAMMAR, opts);
}
`;
fs.writeFileSync(path.join(ROOT, 'dist', 'validate.mjs'), module);

const kb = f => (fs.statSync(path.join(ROOT, 'dist', f)).size / 1024).toFixed(1) + ' KB';
console.log(`dist/grammar.runtime.json ${kb('grammar.runtime.json')}, dist/validate.mjs ${kb('validate.mjs')}`);
